# Generated by Django 2.0.2 on 2018-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('img_url', models.CharField(max_length=200)),
                ('choice', models.TextField()),
                ('open', models.BooleanField()),
            ],
        ),
    ]
