# Generated by Django 2.0.2 on 2018-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0002_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
