# Generated by Django 2.0.2 on 2018-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0003_auto_20180202_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='open',
            field=models.IntegerField(default=0),
        ),
    ]
