# Generated by Django 2.0.2 on 2018-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0006_gntmmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gntmmodel',
            name='age',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
