# Generated by Django 2.0.2 on 2018-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0007_gntmmodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
