# Generated by Django 2.0.2 on 2018-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0008_auto_20180205_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='canswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
