# Generated by Django 2.0.2 on 2018-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0009_auto_20180210_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='etime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
