# Generated by Django 2.0.2 on 2018-02-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0010_challenge_etime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('cid', models.IntegerField()),
                ('aid', models.IntegerField()),
                ('points', models.IntegerField()),
                ('ctype', models.IntegerField()),
                ('ccreator', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('canswer', models.TextField()),
                ('csolution', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
