# Generated by Django 2.0.2 on 2018-02-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cntm', '0011_auto_20180212_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='canswer',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
